### ISSUE TITLE
wemgehoert.de requires recapture?

### ISSUE THREAD

**Issue by mvo5** [bufemc/a1fbox#2]
While running a1fbox example2.py I noticed that the logs show lines like:
```
2020-11-29T10:35:50Z a1fbox-spamblock.blocker[5402]: WARNING:callinfo:404 Client Error: Not Found for url: https://www.wemgehoert.de/recaptcha/xxxxyyyyzzz
```
So it appears that the wemgehoert services does not/no longer work without a capture. Maybe it needs to be disabled by default? Looking at their website it seems they provide real API.

**Comment by bufemc** [comment]
Can you provide the link to the real API? I only found this, which is somehow strange translated (I guess you speak German):

"Ist auch API zur Verfügung?

Die Programmierschnittstelle (API) ist von uns im Rahmen unserer Dienstleistung leider nicht zur Verfügung gestellt und für die Zukunft diese nicht geplant ist"

I approved your PR. It's nice someone is really using my stuff, although it's still no package yet, so please keep in mind the "API" is not yet finalized. There are so many ideas still open, as you can see at the bottom of the README..

**Comment by mvo5** [comment]
@bufemc Thank you! Sorry, what I wrote above was nonsense, I actually wanted to write "they provide *no* real API". Sorry for this.

I really like your project, it's super nice to be able to build a phone spam blocker from example2.py!

I did some work over the weekend to package it as a snap to deploy on a raspberry pi and also wrote a small seutp.py that I needed for the packaging. I hope to find time in the next few days to clean it up a little bit and push here as a PR.

Anyway, huge *THANK YOU* for this repo and your work on this.

**Comment by bufemc** [comment]
It's running on a Raspi 4 here as well, see in README "Autostart on a Raspberry Pi". This was my lazy way.

It might be important to delay the start for some time, it seems the network (especially Wifi) might need some time until it can be used to reach out. Otherwise the call blocker will immediately terminate, maybe I should add a 30 sec waiting loop?

Small PRs are prefered instead of big ones, because if it's too big it really has to adapt/stick to the current coding style. Keep in mind the "API" is totally unfinished.. that's why it's INTENTIONALLY no package and I am not happy yet. Especially CallList is no module, and CallInfo and CallPrefix should be merged somehow IMHO. Big changes could follow.

WemGehoert is indeed a blocker, I already tried to simulate a browser with user agent, but seems this is not enough. Maybe should provide a "combination resolver" which does exclude Wemgehoert.

**Comment by mvo5** [comment]
Thanks for these comments! I keep in mind that the API is not stable. And about the small PRs (but that will just happen by itself as I don't have much time unfortunately).

About the network, I put the example2.py into a systemd service as part of the snap so basic networking will be available via systemd dependencies and even if it dies systemd will just restart it again so eventually it will work. So I think it's fine to not do anything on the application level about this.

And API changes are's fine too, I am mostly interested in the project because of "example2.py" so as long as that keeps getting updated I'm fine :) I guess what I'm trying to say is that it's super useful for me as is already.

**Comment by bufemc** [comment]
As can be seen above this issue has been adressed by now, so I may close it. Feel free to re-open it, if there should be any side effects.
